### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by nestorac** [theCheeseboard/theFrisbee#2]
Hello again! Do you have any documentation for this app and it's library? I'm not sure if I better fork the app and trim the code that I don't need or just build and install your libs and use them as libraries (advice is welcome). Thank you!

**Comment by nestorac** [comment]
I have forgotten to directly ask you if you know the lines of code needed to list all physical disks attached to the computer.

**Comment by vicr123** [comment]
So sorry for not getting back to you earlier. 

Documentation: I haven't really written any documentation about the library but it very closely follows the udisks interfaces in the link I sent in #1.

Fork or copy: It's probably better at this point for you just to take the code you need and pop it into your app, especially since the library's API is not stable yet, so stuff my change

Enumerating disks: Take a look at the methods found in the `DriveObjectManager` class. Hopefully you'll find what you need there 🙃

Hope this helps!
